# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bellman_ford <- function(edges, vertex_source) {
    invisible(.Call('_Pathfinding_bellman_ford', PACKAGE = 'Pathfinding', edges, vertex_source))
}

distMin <- function(distance, visited, n) {
    .Call('_Pathfinding_distMin', PACKAGE = 'Pathfinding', distance, visited, n)
}

printPath <- function(parent, j) {
    invisible(.Call('_Pathfinding_printPath', PACKAGE = 'Pathfinding', parent, j))
}

printSolution <- function(dist, n, parent) {
    invisible(.Call('_Pathfinding_printSolution', PACKAGE = 'Pathfinding', dist, n, parent))
}

dijkstra_cpp <- function(edges) {
    invisible(.Call('_Pathfinding_dijkstra_cpp', PACKAGE = 'Pathfinding', edges))
}

